name: skillswap
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Base Packages
  cupertino_icons: ^1.0.8

  # Firebase Services (Core, Auth, Firestore)
  firebase_core: ^2.27.1
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0

  # State Management
  provider: ^6.1.2

  # Icons & Utilities
  # Risoluzione del conflitto: usiamo la versione compatibile suggerita
  lucide_icons: ^0.257.0
  uuid: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
