name: skillswap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Base Packages
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Utilities
  path_provider: ^2.1.2
  palette_generator: ^0.3.3

  image_picker: ^1.1.2
  # Icons & Utilities
  lucide_icons: ^0.257.0
  uuid: ^4.3.1

  # Navigation
  go_router: ^16.2.5

  bloc: any
  material_color_utilities: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  material_color_utilities: any
flutter:
  uses-material-design: true

  assets:
    - assets/data/users.json
    - assets/data/match_requests.json
    - assets/images/logo.png
    - assets/images/logo_no_bg.png
    - assets/images/background_color.png
    - assets/images/splash_art.gif
    - assets/images/verified.png
