name: skillswap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Base Packages
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: any

  # Utilities
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3
  palette_generator: ^0.3.3
  image_picker: ^1.1.2
  uuid: ^4.3.1
  material_color_utilities: any

  # Icons & Utilities
  lucide_icons: ^0.257.0
  go_router: ^16.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/users.json
    - assets/images/logo.png
    - assets/images/logo_no_bg.png
    - assets/images/background_color.png
    - assets/images/splash_art.gif
    - assets/images/verified.png
    - assets/images/users/mario/mario1.jpg
    - assets/images/users/mario/mario2.jpg
    - assets/images/users/mario/mario3.jpg
    - assets/images/users/mario/mario4.jpeg
    - assets/images/users/laura/laura1.jpg
    - assets/images/users/laura/laura2.jpg
    - assets/images/users/laura/laura3.jpg
    - assets/images/users/laura/laura4.jpg
    - assets/images/users/gio/gio1.jpg
    - assets/images/users/gio/gio2.jpg
    - assets/images/users/gio/gio3.jpg
    - assets/images/users/gio/gio4.jpg
    - assets/images/users/anna/anna1.jpg
    - assets/images/users/anna/anna2.jpg
    - assets/images/users/anna/anna3.jpg
    - assets/images/users/anna/anna4.jpg
    - assets/images/users/luca/luca1.jpg
    - assets/images/users/luca/luca2.jpeg
    - assets/images/users/luca/luca3.jpg
    - assets/images/users/luca/luca4.jpg
    - assets/images/users/ame/ame1.jpg
    - assets/images/users/ame/ame2.jpg
    - assets/images/users/ame/ame3.jpg
    - assets/images/users/ame/ame4.jpg
